### ISSUE TITLE
port variable is wrong on tcp/445

### ISSUE THREAD

**Issue by trentwiles** [tbiens/icarus#4]
On scans to tcp/445 the port variable returns 20445
![Screenshot_20210926-183339_DuckDuckGo](https://user-images.githubusercontent.com/59586759/134826374-c9af1a85-dbb5-443d-a442-e92771cc530e.jpg)

**Comment by tbiens** [comment]
Hello,

Good catch, that makes sense. Inside the docker the app runs as just a user, therefore can't run on ports <1024. Instead I create a docker NAT that makes 445 the public port. Thus breaking the reporting that I recently added.

I pushed a fix, it'll look at a dictionary of the nats and pick the real port.

Testing shows: 


11 seconds ago | 212.253.195.20 triggered Icarus honeypot on port 445. Check us out on github.
-- | --


a simple git pull in the folder and you should be up and running. Thanks for reporting the bug!
