### ISSUE TITLE
Multiple IP's

### ISSUE THREAD

**Issue by evwltrs** [tbiens/icarus#6]
Do you know how I can get Icarus to monitor 2 IP's simultaniously.

Right now I recieve the error
```
configparser.DuplicateOptionError: While reading from 'icarus.config' [line  5]: option 'ip' in section 'ADDRESSES' already exists
```

**Comment by tbiens** [comment]
Hello,

It looks like you're adding a second line in cfg. 

"auto" as the default means 0.0.0.0.  So it should pick up any address. The config file IP setting mostly is about limiting addresses to a specific IP, incase you do have more than 1 and dont wish to use all. 

I suppose something I should test is how it handles multiple interfaces. Is that what you're doing?
